# Generated by Django 5.0.3 on 2024-03-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0001_create_task_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.CharField(choices=[('london', 'London'), ('paris', 'Berlin'), ('wroclaw', 'Wroclaw')], max_length=20, null=True),
        ),
    ]
